/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: common.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "common.pb-c.h"
void   rpc__request__init
                     (Rpc__Request         *message)
{
  static const Rpc__Request init_value = RPC__REQUEST__INIT;
  *message = init_value;
}
size_t rpc__request__get_packed_size
                     (const Rpc__Request *message)
{
  assert(message->base.descriptor == &rpc__request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc__request__pack
                     (const Rpc__Request *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpc__request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc__request__pack_to_buffer
                     (const Rpc__Request *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpc__request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rpc__Request *
       rpc__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rpc__Request *)
     protobuf_c_message_unpack (&rpc__request__descriptor,
                                allocator, len, data);
}
void   rpc__request__free_unpacked
                     (Rpc__Request *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rpc__request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpc__response__init
                     (Rpc__Response         *message)
{
  static const Rpc__Response init_value = RPC__RESPONSE__INIT;
  *message = init_value;
}
size_t rpc__response__get_packed_size
                     (const Rpc__Response *message)
{
  assert(message->base.descriptor == &rpc__response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc__response__pack
                     (const Rpc__Response *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpc__response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc__response__pack_to_buffer
                     (const Rpc__Response *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpc__response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rpc__Response *
       rpc__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rpc__Response *)
     protobuf_c_message_unpack (&rpc__response__descriptor,
                                allocator, len, data);
}
void   rpc__response__free_unpacked
                     (Rpc__Response *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rpc__response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor rpc__request__field_descriptors[1] =
{
  {
    "number",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Rpc__Request, number),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc__request__field_indices_by_name[] = {
  0,   /* field[0] = number */
};
static const ProtobufCIntRange rpc__request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rpc__request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Rpc.Request",
  "Request",
  "Rpc__Request",
  "Rpc",
  sizeof(Rpc__Request),
  1,
  rpc__request__field_descriptors,
  rpc__request__field_indices_by_name,
  1,  rpc__request__number_ranges,
  (ProtobufCMessageInit) rpc__request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpc__response__field_descriptors[1] =
{
  {
    "result",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Rpc__Response, result),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc__response__field_indices_by_name[] = {
  0,   /* field[0] = result */
};
static const ProtobufCIntRange rpc__response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rpc__response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Rpc.Response",
  "Response",
  "Rpc__Response",
  "Rpc",
  sizeof(Rpc__Response),
  1,
  rpc__response__field_descriptors,
  rpc__response__field_indices_by_name,
  1,  rpc__response__number_ranges,
  (ProtobufCMessageInit) rpc__response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCMethodDescriptor rpc__multiplication__method_descriptors[1] =
{
  { "Multiply", &rpc__request__descriptor, &rpc__response__descriptor },
};
const unsigned rpc__multiplication__method_indices_by_name[] = {
  0         /* Multiply */
};
const ProtobufCServiceDescriptor rpc__multiplication__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "Rpc.Multiplication",
  "Multiplication",
  "Rpc__Multiplication",
  "Rpc",
  1,
  rpc__multiplication__method_descriptors,
  rpc__multiplication__method_indices_by_name
};
void rpc__multiplication__multiply(ProtobufCService *service,
                                   const Rpc__Request *input,
                                   Rpc__Response_Closure closure,
                                   void *closure_data)
{
  assert(service->descriptor == &rpc__multiplication__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void rpc__multiplication__init (Rpc__Multiplication_Service *service,
                                Rpc__Multiplication_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &rpc__multiplication__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
