/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: common.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "common.pb-c.h"
void   rpc__file_info__init
                     (Rpc__FileInfo         *message)
{
  static const Rpc__FileInfo init_value = RPC__FILE_INFO__INIT;
  *message = init_value;
}
size_t rpc__file_info__get_packed_size
                     (const Rpc__FileInfo *message)
{
  assert(message->base.descriptor == &rpc__file_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc__file_info__pack
                     (const Rpc__FileInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpc__file_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc__file_info__pack_to_buffer
                     (const Rpc__FileInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpc__file_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rpc__FileInfo *
       rpc__file_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rpc__FileInfo *)
     protobuf_c_message_unpack (&rpc__file_info__descriptor,
                                allocator, len, data);
}
void   rpc__file_info__free_unpacked
                     (Rpc__FileInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rpc__file_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpc__node_id__init
                     (Rpc__NodeId         *message)
{
  static const Rpc__NodeId init_value = RPC__NODE_ID__INIT;
  *message = init_value;
}
size_t rpc__node_id__get_packed_size
                     (const Rpc__NodeId *message)
{
  assert(message->base.descriptor == &rpc__node_id__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc__node_id__pack
                     (const Rpc__NodeId *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpc__node_id__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc__node_id__pack_to_buffer
                     (const Rpc__NodeId *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpc__node_id__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rpc__NodeId *
       rpc__node_id__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rpc__NodeId *)
     protobuf_c_message_unpack (&rpc__node_id__descriptor,
                                allocator, len, data);
}
void   rpc__node_id__free_unpacked
                     (Rpc__NodeId *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rpc__node_id__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpc__node_value__init
                     (Rpc__NodeValue         *message)
{
  static const Rpc__NodeValue init_value = RPC__NODE_VALUE__INIT;
  *message = init_value;
}
size_t rpc__node_value__get_packed_size
                     (const Rpc__NodeValue *message)
{
  assert(message->base.descriptor == &rpc__node_value__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc__node_value__pack
                     (const Rpc__NodeValue *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpc__node_value__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc__node_value__pack_to_buffer
                     (const Rpc__NodeValue *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpc__node_value__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rpc__NodeValue *
       rpc__node_value__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rpc__NodeValue *)
     protobuf_c_message_unpack (&rpc__node_value__descriptor,
                                allocator, len, data);
}
void   rpc__node_value__free_unpacked
                     (Rpc__NodeValue *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rpc__node_value__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpc__filter__init
                     (Rpc__Filter         *message)
{
  static const Rpc__Filter init_value = RPC__FILTER__INIT;
  *message = init_value;
}
size_t rpc__filter__get_packed_size
                     (const Rpc__Filter *message)
{
  assert(message->base.descriptor == &rpc__filter__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc__filter__pack
                     (const Rpc__Filter *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpc__filter__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc__filter__pack_to_buffer
                     (const Rpc__Filter *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpc__filter__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rpc__Filter *
       rpc__filter__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rpc__Filter *)
     protobuf_c_message_unpack (&rpc__filter__descriptor,
                                allocator, len, data);
}
void   rpc__filter__free_unpacked
                     (Rpc__Filter *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rpc__filter__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpc__filter_chain__init
                     (Rpc__FilterChain         *message)
{
  static const Rpc__FilterChain init_value = RPC__FILTER_CHAIN__INIT;
  *message = init_value;
}
size_t rpc__filter_chain__get_packed_size
                     (const Rpc__FilterChain *message)
{
  assert(message->base.descriptor == &rpc__filter_chain__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc__filter_chain__pack
                     (const Rpc__FilterChain *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpc__filter_chain__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc__filter_chain__pack_to_buffer
                     (const Rpc__FilterChain *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpc__filter_chain__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rpc__FilterChain *
       rpc__filter_chain__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rpc__FilterChain *)
     protobuf_c_message_unpack (&rpc__filter_chain__descriptor,
                                allocator, len, data);
}
void   rpc__filter_chain__free_unpacked
                     (Rpc__FilterChain *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rpc__filter_chain__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpc__nodes__init
                     (Rpc__Nodes         *message)
{
  static const Rpc__Nodes init_value = RPC__NODES__INIT;
  *message = init_value;
}
size_t rpc__nodes__get_packed_size
                     (const Rpc__Nodes *message)
{
  assert(message->base.descriptor == &rpc__nodes__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc__nodes__pack
                     (const Rpc__Nodes *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpc__nodes__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc__nodes__pack_to_buffer
                     (const Rpc__Nodes *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpc__nodes__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rpc__Nodes *
       rpc__nodes__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rpc__Nodes *)
     protobuf_c_message_unpack (&rpc__nodes__descriptor,
                                allocator, len, data);
}
void   rpc__nodes__free_unpacked
                     (Rpc__Nodes *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rpc__nodes__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpc__node__init
                     (Rpc__Node         *message)
{
  static const Rpc__Node init_value = RPC__NODE__INIT;
  *message = init_value;
}
size_t rpc__node__get_packed_size
                     (const Rpc__Node *message)
{
  assert(message->base.descriptor == &rpc__node__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc__node__pack
                     (const Rpc__Node *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpc__node__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc__node__pack_to_buffer
                     (const Rpc__Node *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpc__node__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rpc__Node *
       rpc__node__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rpc__Node *)
     protobuf_c_message_unpack (&rpc__node__descriptor,
                                allocator, len, data);
}
void   rpc__node__free_unpacked
                     (Rpc__Node *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rpc__node__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpc__create_node_request__init
                     (Rpc__CreateNodeRequest         *message)
{
  static const Rpc__CreateNodeRequest init_value = RPC__CREATE_NODE_REQUEST__INIT;
  *message = init_value;
}
size_t rpc__create_node_request__get_packed_size
                     (const Rpc__CreateNodeRequest *message)
{
  assert(message->base.descriptor == &rpc__create_node_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc__create_node_request__pack
                     (const Rpc__CreateNodeRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpc__create_node_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc__create_node_request__pack_to_buffer
                     (const Rpc__CreateNodeRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpc__create_node_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rpc__CreateNodeRequest *
       rpc__create_node_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rpc__CreateNodeRequest *)
     protobuf_c_message_unpack (&rpc__create_node_request__descriptor,
                                allocator, len, data);
}
void   rpc__create_node_request__free_unpacked
                     (Rpc__CreateNodeRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rpc__create_node_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpc__update_node_request__init
                     (Rpc__UpdateNodeRequest         *message)
{
  static const Rpc__UpdateNodeRequest init_value = RPC__UPDATE_NODE_REQUEST__INIT;
  *message = init_value;
}
size_t rpc__update_node_request__get_packed_size
                     (const Rpc__UpdateNodeRequest *message)
{
  assert(message->base.descriptor == &rpc__update_node_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc__update_node_request__pack
                     (const Rpc__UpdateNodeRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpc__update_node_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc__update_node_request__pack_to_buffer
                     (const Rpc__UpdateNodeRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpc__update_node_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rpc__UpdateNodeRequest *
       rpc__update_node_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rpc__UpdateNodeRequest *)
     protobuf_c_message_unpack (&rpc__update_node_request__descriptor,
                                allocator, len, data);
}
void   rpc__update_node_request__free_unpacked
                     (Rpc__UpdateNodeRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rpc__update_node_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpc__delete_node_request__init
                     (Rpc__DeleteNodeRequest         *message)
{
  static const Rpc__DeleteNodeRequest init_value = RPC__DELETE_NODE_REQUEST__INIT;
  *message = init_value;
}
size_t rpc__delete_node_request__get_packed_size
                     (const Rpc__DeleteNodeRequest *message)
{
  assert(message->base.descriptor == &rpc__delete_node_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc__delete_node_request__pack
                     (const Rpc__DeleteNodeRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpc__delete_node_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc__delete_node_request__pack_to_buffer
                     (const Rpc__DeleteNodeRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpc__delete_node_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rpc__DeleteNodeRequest *
       rpc__delete_node_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rpc__DeleteNodeRequest *)
     protobuf_c_message_unpack (&rpc__delete_node_request__descriptor,
                                allocator, len, data);
}
void   rpc__delete_node_request__free_unpacked
                     (Rpc__DeleteNodeRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rpc__delete_node_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpc__deleted_nodes__init
                     (Rpc__DeletedNodes         *message)
{
  static const Rpc__DeletedNodes init_value = RPC__DELETED_NODES__INIT;
  *message = init_value;
}
size_t rpc__deleted_nodes__get_packed_size
                     (const Rpc__DeletedNodes *message)
{
  assert(message->base.descriptor == &rpc__deleted_nodes__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc__deleted_nodes__pack
                     (const Rpc__DeletedNodes *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpc__deleted_nodes__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc__deleted_nodes__pack_to_buffer
                     (const Rpc__DeletedNodes *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpc__deleted_nodes__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rpc__DeletedNodes *
       rpc__deleted_nodes__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rpc__DeletedNodes *)
     protobuf_c_message_unpack (&rpc__deleted_nodes__descriptor,
                                allocator, len, data);
}
void   rpc__deleted_nodes__free_unpacked
                     (Rpc__DeletedNodes *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rpc__deleted_nodes__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor rpc__file_info__field_descriptors[4] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Rpc__FileInfo, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "owner",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Rpc__FileInfo, owner),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "access_time",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Rpc__FileInfo, access_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mime_type",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Rpc__FileInfo, mime_type),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc__file_info__field_indices_by_name[] = {
  2,   /* field[2] = access_time */
  3,   /* field[3] = mime_type */
  0,   /* field[0] = name */
  1,   /* field[1] = owner */
};
static const ProtobufCIntRange rpc__file_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor rpc__file_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Rpc.FileInfo",
  "FileInfo",
  "Rpc__FileInfo",
  "Rpc",
  sizeof(Rpc__FileInfo),
  4,
  rpc__file_info__field_descriptors,
  rpc__file_info__field_indices_by_name,
  1,  rpc__file_info__number_ranges,
  (ProtobufCMessageInit) rpc__file_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpc__node_id__field_descriptors[2] =
{
  {
    "page_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Rpc__NodeId, page_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "item_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Rpc__NodeId, item_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc__node_id__field_indices_by_name[] = {
  1,   /* field[1] = item_id */
  0,   /* field[0] = page_id */
};
static const ProtobufCIntRange rpc__node_id__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor rpc__node_id__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Rpc.NodeId",
  "NodeId",
  "Rpc__NodeId",
  "Rpc",
  sizeof(Rpc__NodeId),
  2,
  rpc__node_id__field_descriptors,
  rpc__node_id__field_indices_by_name,
  1,  rpc__node_id__number_ranges,
  (ProtobufCMessageInit) rpc__node_id__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue rpc__node_value__type__enum_values_by_number[6] =
{
  { "UNKNOWN", "RPC__NODE_VALUE__TYPE__UNKNOWN", 0 },
  { "INT_32", "RPC__NODE_VALUE__TYPE__INT_32", 1 },
  { "DOUBLE", "RPC__NODE_VALUE__TYPE__DOUBLE", 2 },
  { "STRING", "RPC__NODE_VALUE__TYPE__STRING", 3 },
  { "BOOL", "RPC__NODE_VALUE__TYPE__BOOL", 4 },
  { "FILE_INFO", "RPC__NODE_VALUE__TYPE__FILE_INFO", 5 },
};
static const ProtobufCIntRange rpc__node_value__type__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex rpc__node_value__type__enum_values_by_name[6] =
{
  { "BOOL", 4 },
  { "DOUBLE", 2 },
  { "FILE_INFO", 5 },
  { "INT_32", 1 },
  { "STRING", 3 },
  { "UNKNOWN", 0 },
};
const ProtobufCEnumDescriptor rpc__node_value__type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Rpc.NodeValue.Type",
  "Type",
  "Rpc__NodeValue__Type",
  "Rpc",
  6,
  rpc__node_value__type__enum_values_by_number,
  6,
  rpc__node_value__type__enum_values_by_name,
  1,
  rpc__node_value__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor rpc__node_value__field_descriptors[6] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Rpc__NodeValue, type),
    &rpc__node_value__type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "int_value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Rpc__NodeValue, value_case),
    offsetof(Rpc__NodeValue, int_value),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "double_value",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Rpc__NodeValue, value_case),
    offsetof(Rpc__NodeValue, double_value),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "string_value",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Rpc__NodeValue, value_case),
    offsetof(Rpc__NodeValue, string_value),
    NULL,
    &protobuf_c_empty_string,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bool_value",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Rpc__NodeValue, value_case),
    offsetof(Rpc__NodeValue, bool_value),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "file_info_value",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Rpc__NodeValue, value_case),
    offsetof(Rpc__NodeValue, file_info_value),
    &rpc__file_info__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc__node_value__field_indices_by_name[] = {
  4,   /* field[4] = bool_value */
  2,   /* field[2] = double_value */
  5,   /* field[5] = file_info_value */
  1,   /* field[1] = int_value */
  3,   /* field[3] = string_value */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange rpc__node_value__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor rpc__node_value__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Rpc.NodeValue",
  "NodeValue",
  "Rpc__NodeValue",
  "Rpc",
  sizeof(Rpc__NodeValue),
  6,
  rpc__node_value__field_descriptors,
  rpc__node_value__field_indices_by_name,
  1,  rpc__node_value__number_ranges,
  (ProtobufCMessageInit) rpc__node_value__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue rpc__filter__type__enum_values_by_number[7] =
{
  { "UNKNOWN_TYPE", "RPC__FILTER__TYPE__UNKNOWN_TYPE", 0 },
  { "GREATER", "RPC__FILTER__TYPE__GREATER", 1 },
  { "LESS", "RPC__FILTER__TYPE__LESS", 2 },
  { "EQUAL", "RPC__FILTER__TYPE__EQUAL", 3 },
  { "NOT_EQUAL", "RPC__FILTER__TYPE__NOT_EQUAL", 4 },
  { "ALL", "RPC__FILTER__TYPE__ALL", 5 },
  { "FIELD_NAME", "RPC__FILTER__TYPE__FIELD_NAME", 6 },
};
static const ProtobufCIntRange rpc__filter__type__value_ranges[] = {
{0, 0},{0, 7}
};
static const ProtobufCEnumValueIndex rpc__filter__type__enum_values_by_name[7] =
{
  { "ALL", 5 },
  { "EQUAL", 3 },
  { "FIELD_NAME", 6 },
  { "GREATER", 1 },
  { "LESS", 2 },
  { "NOT_EQUAL", 4 },
  { "UNKNOWN_TYPE", 0 },
};
const ProtobufCEnumDescriptor rpc__filter__type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Rpc.Filter.Type",
  "Type",
  "Rpc__Filter__Type",
  "Rpc",
  7,
  rpc__filter__type__enum_values_by_number,
  7,
  rpc__filter__type__enum_values_by_name,
  1,
  rpc__filter__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor rpc__filter__field_descriptors[6] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Rpc__Filter, type),
    &rpc__filter__type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "int_argument",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Rpc__Filter, argument_case),
    offsetof(Rpc__Filter, int_argument),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "double_argument",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Rpc__Filter, argument_case),
    offsetof(Rpc__Filter, double_argument),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "string_argument",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Rpc__Filter, argument_case),
    offsetof(Rpc__Filter, string_argument),
    NULL,
    &protobuf_c_empty_string,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bool_argument",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Rpc__Filter, argument_case),
    offsetof(Rpc__Filter, bool_argument),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Rpc__Filter, field_name_case),
    offsetof(Rpc__Filter, name),
    NULL,
    &protobuf_c_empty_string,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc__filter__field_indices_by_name[] = {
  4,   /* field[4] = bool_argument */
  2,   /* field[2] = double_argument */
  1,   /* field[1] = int_argument */
  5,   /* field[5] = name */
  3,   /* field[3] = string_argument */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange rpc__filter__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor rpc__filter__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Rpc.Filter",
  "Filter",
  "Rpc__Filter",
  "Rpc",
  sizeof(Rpc__Filter),
  6,
  rpc__filter__field_descriptors,
  rpc__filter__field_indices_by_name,
  1,  rpc__filter__number_ranges,
  (ProtobufCMessageInit) rpc__filter__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpc__filter_chain__field_descriptors[1] =
{
  {
    "filters",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Rpc__FilterChain, n_filters),
    offsetof(Rpc__FilterChain, filters),
    &rpc__filter__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc__filter_chain__field_indices_by_name[] = {
  0,   /* field[0] = filters */
};
static const ProtobufCIntRange rpc__filter_chain__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rpc__filter_chain__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Rpc.FilterChain",
  "FilterChain",
  "Rpc__FilterChain",
  "Rpc",
  sizeof(Rpc__FilterChain),
  1,
  rpc__filter_chain__field_descriptors,
  rpc__filter_chain__field_indices_by_name,
  1,  rpc__filter_chain__number_ranges,
  (ProtobufCMessageInit) rpc__filter_chain__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpc__nodes__field_descriptors[1] =
{
  {
    "nodes",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Rpc__Nodes, n_nodes),
    offsetof(Rpc__Nodes, nodes),
    &rpc__node__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc__nodes__field_indices_by_name[] = {
  0,   /* field[0] = nodes */
};
static const ProtobufCIntRange rpc__nodes__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rpc__nodes__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Rpc.Nodes",
  "Nodes",
  "Rpc__Nodes",
  "Rpc",
  sizeof(Rpc__Nodes),
  1,
  rpc__nodes__field_descriptors,
  rpc__nodes__field_indices_by_name,
  1,  rpc__nodes__number_ranges,
  (ProtobufCMessageInit) rpc__nodes__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpc__node__field_descriptors[3] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Rpc__Node, id),
    &rpc__node_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "parent_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Rpc__Node, parent_id),
    &rpc__node_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Rpc__Node, value),
    &rpc__node_value__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc__node__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = parent_id */
  2,   /* field[2] = value */
};
static const ProtobufCIntRange rpc__node__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor rpc__node__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Rpc.Node",
  "Node",
  "Rpc__Node",
  "Rpc",
  sizeof(Rpc__Node),
  3,
  rpc__node__field_descriptors,
  rpc__node__field_indices_by_name,
  1,  rpc__node__number_ranges,
  (ProtobufCMessageInit) rpc__node__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpc__create_node_request__field_descriptors[2] =
{
  {
    "value",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Rpc__CreateNodeRequest, value),
    &rpc__node_value__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "parent_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Rpc__CreateNodeRequest, parent_id),
    &rpc__node_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc__create_node_request__field_indices_by_name[] = {
  1,   /* field[1] = parent_id */
  0,   /* field[0] = value */
};
static const ProtobufCIntRange rpc__create_node_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor rpc__create_node_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Rpc.CreateNodeRequest",
  "CreateNodeRequest",
  "Rpc__CreateNodeRequest",
  "Rpc",
  sizeof(Rpc__CreateNodeRequest),
  2,
  rpc__create_node_request__field_descriptors,
  rpc__create_node_request__field_indices_by_name,
  1,  rpc__create_node_request__number_ranges,
  (ProtobufCMessageInit) rpc__create_node_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpc__update_node_request__field_descriptors[3] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Rpc__UpdateNodeRequest, id),
    &rpc__node_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "parent_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Rpc__UpdateNodeRequest, parent_id),
    &rpc__node_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Rpc__UpdateNodeRequest, value),
    &rpc__node_value__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc__update_node_request__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = parent_id */
  2,   /* field[2] = value */
};
static const ProtobufCIntRange rpc__update_node_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor rpc__update_node_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Rpc.UpdateNodeRequest",
  "UpdateNodeRequest",
  "Rpc__UpdateNodeRequest",
  "Rpc",
  sizeof(Rpc__UpdateNodeRequest),
  3,
  rpc__update_node_request__field_descriptors,
  rpc__update_node_request__field_indices_by_name,
  1,  rpc__update_node_request__number_ranges,
  (ProtobufCMessageInit) rpc__update_node_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpc__delete_node_request__field_descriptors[1] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Rpc__DeleteNodeRequest, id),
    &rpc__node_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc__delete_node_request__field_indices_by_name[] = {
  0,   /* field[0] = id */
};
static const ProtobufCIntRange rpc__delete_node_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rpc__delete_node_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Rpc.DeleteNodeRequest",
  "DeleteNodeRequest",
  "Rpc__DeleteNodeRequest",
  "Rpc",
  sizeof(Rpc__DeleteNodeRequest),
  1,
  rpc__delete_node_request__field_descriptors,
  rpc__delete_node_request__field_indices_by_name,
  1,  rpc__delete_node_request__number_ranges,
  (ProtobufCMessageInit) rpc__delete_node_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpc__deleted_nodes__field_descriptors[1] =
{
  {
    "count",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Rpc__DeletedNodes, count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc__deleted_nodes__field_indices_by_name[] = {
  0,   /* field[0] = count */
};
static const ProtobufCIntRange rpc__deleted_nodes__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rpc__deleted_nodes__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Rpc.DeletedNodes",
  "DeletedNodes",
  "Rpc__DeletedNodes",
  "Rpc",
  sizeof(Rpc__DeletedNodes),
  1,
  rpc__deleted_nodes__field_descriptors,
  rpc__deleted_nodes__field_indices_by_name,
  1,  rpc__deleted_nodes__number_ranges,
  (ProtobufCMessageInit) rpc__deleted_nodes__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCMethodDescriptor rpc__database__method_descriptors[6] =
{
  { "CreateNode", &rpc__create_node_request__descriptor, &rpc__node__descriptor },
  { "UpdateNode", &rpc__update_node_request__descriptor, &rpc__node__descriptor },
  { "DeleteNode", &rpc__delete_node_request__descriptor, &rpc__node__descriptor },
  { "GetNode", &rpc__node_id__descriptor, &rpc__node__descriptor },
  { "GetNodesByFilter", &rpc__filter_chain__descriptor, &rpc__nodes__descriptor },
  { "DeleteNodesByFilter", &rpc__filter_chain__descriptor, &rpc__deleted_nodes__descriptor },
};
const unsigned rpc__database__method_indices_by_name[] = {
  0,        /* CreateNode */
  2,        /* DeleteNode */
  5,        /* DeleteNodesByFilter */
  3,        /* GetNode */
  4,        /* GetNodesByFilter */
  1         /* UpdateNode */
};
const ProtobufCServiceDescriptor rpc__database__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "Rpc.Database",
  "Database",
  "Rpc__Database",
  "Rpc",
  6,
  rpc__database__method_descriptors,
  rpc__database__method_indices_by_name
};
void rpc__database__create_node(ProtobufCService *service,
                                const Rpc__CreateNodeRequest *input,
                                Rpc__Node_Closure closure,
                                void *closure_data)
{
  assert(service->descriptor == &rpc__database__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void rpc__database__update_node(ProtobufCService *service,
                                const Rpc__UpdateNodeRequest *input,
                                Rpc__Node_Closure closure,
                                void *closure_data)
{
  assert(service->descriptor == &rpc__database__descriptor);
  service->invoke(service, 1, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void rpc__database__delete_node(ProtobufCService *service,
                                const Rpc__DeleteNodeRequest *input,
                                Rpc__Node_Closure closure,
                                void *closure_data)
{
  assert(service->descriptor == &rpc__database__descriptor);
  service->invoke(service, 2, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void rpc__database__get_node(ProtobufCService *service,
                             const Rpc__NodeId *input,
                             Rpc__Node_Closure closure,
                             void *closure_data)
{
  assert(service->descriptor == &rpc__database__descriptor);
  service->invoke(service, 3, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void rpc__database__get_nodes_by_filter(ProtobufCService *service,
                                        const Rpc__FilterChain *input,
                                        Rpc__Nodes_Closure closure,
                                        void *closure_data)
{
  assert(service->descriptor == &rpc__database__descriptor);
  service->invoke(service, 4, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void rpc__database__delete_nodes_by_filter(ProtobufCService *service,
                                           const Rpc__FilterChain *input,
                                           Rpc__DeletedNodes_Closure closure,
                                           void *closure_data)
{
  assert(service->descriptor == &rpc__database__descriptor);
  service->invoke(service, 5, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void rpc__database__init (Rpc__Database_Service *service,
                          Rpc__Database_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &rpc__database__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
