/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: common.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "common.pb-c.h"
void   rpc__file_info__init
                     (Rpc__FileInfo         *message)
{
  static const Rpc__FileInfo init_value = RPC__FILE_INFO__INIT;
  *message = init_value;
}
size_t rpc__file_info__get_packed_size
                     (const Rpc__FileInfo *message)
{
  assert(message->base.descriptor == &rpc__file_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc__file_info__pack
                     (const Rpc__FileInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpc__file_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc__file_info__pack_to_buffer
                     (const Rpc__FileInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpc__file_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rpc__FileInfo *
       rpc__file_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rpc__FileInfo *)
     protobuf_c_message_unpack (&rpc__file_info__descriptor,
                                allocator, len, data);
}
void   rpc__file_info__free_unpacked
                     (Rpc__FileInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rpc__file_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpc__node_id__init
                     (Rpc__NodeId         *message)
{
  static const Rpc__NodeId init_value = RPC__NODE_ID__INIT;
  *message = init_value;
}
size_t rpc__node_id__get_packed_size
                     (const Rpc__NodeId *message)
{
  assert(message->base.descriptor == &rpc__node_id__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc__node_id__pack
                     (const Rpc__NodeId *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpc__node_id__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc__node_id__pack_to_buffer
                     (const Rpc__NodeId *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpc__node_id__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rpc__NodeId *
       rpc__node_id__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rpc__NodeId *)
     protobuf_c_message_unpack (&rpc__node_id__descriptor,
                                allocator, len, data);
}
void   rpc__node_id__free_unpacked
                     (Rpc__NodeId *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rpc__node_id__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpc__create_file_node_request__init
                     (Rpc__CreateFileNodeRequest         *message)
{
  static const Rpc__CreateFileNodeRequest init_value = RPC__CREATE_FILE_NODE_REQUEST__INIT;
  *message = init_value;
}
size_t rpc__create_file_node_request__get_packed_size
                     (const Rpc__CreateFileNodeRequest *message)
{
  assert(message->base.descriptor == &rpc__create_file_node_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc__create_file_node_request__pack
                     (const Rpc__CreateFileNodeRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpc__create_file_node_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc__create_file_node_request__pack_to_buffer
                     (const Rpc__CreateFileNodeRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpc__create_file_node_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rpc__CreateFileNodeRequest *
       rpc__create_file_node_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rpc__CreateFileNodeRequest *)
     protobuf_c_message_unpack (&rpc__create_file_node_request__descriptor,
                                allocator, len, data);
}
void   rpc__create_file_node_request__free_unpacked
                     (Rpc__CreateFileNodeRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rpc__create_file_node_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpc__create_file_node_response__init
                     (Rpc__CreateFileNodeResponse         *message)
{
  static const Rpc__CreateFileNodeResponse init_value = RPC__CREATE_FILE_NODE_RESPONSE__INIT;
  *message = init_value;
}
size_t rpc__create_file_node_response__get_packed_size
                     (const Rpc__CreateFileNodeResponse *message)
{
  assert(message->base.descriptor == &rpc__create_file_node_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc__create_file_node_response__pack
                     (const Rpc__CreateFileNodeResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpc__create_file_node_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc__create_file_node_response__pack_to_buffer
                     (const Rpc__CreateFileNodeResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpc__create_file_node_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rpc__CreateFileNodeResponse *
       rpc__create_file_node_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rpc__CreateFileNodeResponse *)
     protobuf_c_message_unpack (&rpc__create_file_node_response__descriptor,
                                allocator, len, data);
}
void   rpc__create_file_node_response__free_unpacked
                     (Rpc__CreateFileNodeResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rpc__create_file_node_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor rpc__file_info__field_descriptors[4] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Rpc__FileInfo, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "owner",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Rpc__FileInfo, owner),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "access_time",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Rpc__FileInfo, access_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mime_type",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Rpc__FileInfo, mime_type),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc__file_info__field_indices_by_name[] = {
  2,   /* field[2] = access_time */
  3,   /* field[3] = mime_type */
  0,   /* field[0] = name */
  1,   /* field[1] = owner */
};
static const ProtobufCIntRange rpc__file_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor rpc__file_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Rpc.FileInfo",
  "FileInfo",
  "Rpc__FileInfo",
  "Rpc",
  sizeof(Rpc__FileInfo),
  4,
  rpc__file_info__field_descriptors,
  rpc__file_info__field_indices_by_name,
  1,  rpc__file_info__number_ranges,
  (ProtobufCMessageInit) rpc__file_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpc__node_id__field_descriptors[2] =
{
  {
    "page_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Rpc__NodeId, page_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "item_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Rpc__NodeId, item_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc__node_id__field_indices_by_name[] = {
  1,   /* field[1] = item_id */
  0,   /* field[0] = page_id */
};
static const ProtobufCIntRange rpc__node_id__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor rpc__node_id__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Rpc.NodeId",
  "NodeId",
  "Rpc__NodeId",
  "Rpc",
  sizeof(Rpc__NodeId),
  2,
  rpc__node_id__field_descriptors,
  rpc__node_id__field_indices_by_name,
  1,  rpc__node_id__number_ranges,
  (ProtobufCMessageInit) rpc__node_id__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpc__create_file_node_request__field_descriptors[2] =
{
  {
    "file_info",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Rpc__CreateFileNodeRequest, file_info),
    &rpc__file_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "parent_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Rpc__CreateFileNodeRequest, parent_id),
    &rpc__node_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc__create_file_node_request__field_indices_by_name[] = {
  0,   /* field[0] = file_info */
  1,   /* field[1] = parent_id */
};
static const ProtobufCIntRange rpc__create_file_node_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor rpc__create_file_node_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Rpc.CreateFileNodeRequest",
  "CreateFileNodeRequest",
  "Rpc__CreateFileNodeRequest",
  "Rpc",
  sizeof(Rpc__CreateFileNodeRequest),
  2,
  rpc__create_file_node_request__field_descriptors,
  rpc__create_file_node_request__field_indices_by_name,
  1,  rpc__create_file_node_request__number_ranges,
  (ProtobufCMessageInit) rpc__create_file_node_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpc__create_file_node_response__field_descriptors[1] =
{
  {
    "node_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Rpc__CreateFileNodeResponse, node_id),
    &rpc__node_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc__create_file_node_response__field_indices_by_name[] = {
  0,   /* field[0] = node_id */
};
static const ProtobufCIntRange rpc__create_file_node_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rpc__create_file_node_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Rpc.CreateFileNodeResponse",
  "CreateFileNodeResponse",
  "Rpc__CreateFileNodeResponse",
  "Rpc",
  sizeof(Rpc__CreateFileNodeResponse),
  1,
  rpc__create_file_node_response__field_descriptors,
  rpc__create_file_node_response__field_indices_by_name,
  1,  rpc__create_file_node_response__number_ranges,
  (ProtobufCMessageInit) rpc__create_file_node_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCMethodDescriptor rpc__database__method_descriptors[1] =
{
  { "CreateFileNode", &rpc__create_file_node_request__descriptor, &rpc__create_file_node_response__descriptor },
};
const unsigned rpc__database__method_indices_by_name[] = {
  0         /* CreateFileNode */
};
const ProtobufCServiceDescriptor rpc__database__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "Rpc.Database",
  "Database",
  "Rpc__Database",
  "Rpc",
  1,
  rpc__database__method_descriptors,
  rpc__database__method_indices_by_name
};
void rpc__database__create_file_node(ProtobufCService *service,
                                     const Rpc__CreateFileNodeRequest *input,
                                     Rpc__CreateFileNodeResponse_Closure closure,
                                     void *closure_data)
{
  assert(service->descriptor == &rpc__database__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void rpc__database__init (Rpc__Database_Service *service,
                          Rpc__Database_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &rpc__database__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
